In [2]:
import tensorflow as tf
import numpy as np
if tf.__version__ < "2.0.0":
  !pip install --upgrade tensorflow_gpu==2.0

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [4]:
import pandas as pd
dataframe = pd.read_csv('sonar.all-data' , header = None)

In [7]:
dataframe

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
5    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
6    0.0317  0.0956  0.1321  0.1408  0.1674  0.1710  0.0731  0.1401  0.2083   
7    0.0519  0.0548  0.0842  0.0319  0.1158  0.0922  0.1027  0.0613  0.1465   
8    0.0223  0.0375  0.0484  0.0475  0.0647  0.0591  0.0753  0.0098  0.0684   
9    0.0164  0.0173  0.0347  0.0070  0.0187  0.0671  0.1056  0.0697  0.0962   
10   0.0039  0.0063  0.0152  0.0336  0.0310  0.0284  0.0396  0.0272  0.0323   
11   0.0123  0.0309  0.0169  0.0313  0.0358  0.0102  0.0182  0.0579  0.1122   
12   0.0079  0.0086  0.0055  0.0250  0.0344  0.0546  0.0528  0.0958  0.1009   
13   0.0090  0.0062  0.0253  0.0489  0.1197  0.1589  0.1392  0.0987  0.0955   
14   0.0124  0.0433  0.0604  0.0449  0.0597  0.0355  0.0531  0.0343  0.1052   
15   0.0298  0.0615  0.0650  0.0921  0.1615  0.2294  0.2176  0.2033  0.1459   
16   0.0352  0.0116  0.0191  0.0469  0.0737  0.1185  0.1683  0.1541  0.1466   
17   0.0192  0.0607  0.0378  0.0774  0.1388  0.0809  0.0568  0.0219  0.1037   
18   0.0270  0.0092  0.0145  0.0278  0.0412  0.0757  0.1026  0.1138  0.0794   
19   0.0126  0.0149  0.0641  0.1732  0.2565  0.2559  0.2947  0.4110  0.4983   
20   0.0473  0.0509  0.0819  0.1252  0.1783  0.3070  0.3008  0.2362  0.3830   
21   0.0664  0.0575  0.0842  0.0372  0.0458  0.0771  0.0771  0.1130  0.2353   
22   0.0099  0.0484  0.0299  0.0297  0.0652  0.1077  0.2363  0.2385  0.0075   
23   0.0115  0.0150  0.0136  0.0076  0.0211  0.1058  0.1023  0.0440  0.0931   
24   0.0293  0.0644  0.0390  0.0173  0.0476  0.0816  0.0993  0.0315  0.0736   
25   0.0201  0.0026  0.0138  0.0062  0.0133  0.0151  0.0541  0.0210  0.0505   
26   0.0151  0.0320  0.0599  0.1050  0.1163  0.1734  0.1679  0.1119  0.0889   
27   0.0177  0.0300  0.0288  0.0394  0.0630  0.0526  0.0688  0.0633  0.0624   
28   0.0100  0.0275  0.0190  0.0371  0.0416  0.0201  0.0314  0.0651  0.1896   
29   0.0189  0.0308  0.0197  0.0622  0.0080  0.0789  0.1440  0.1451  0.1789   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
178  0.0197  0.0394  0.0384  0.0076  0.0251  0.0629  0.0747  0.0578  0.1357   
179  0.0394  0.0420  0.0446  0.0551  0.0597  0.1416  0.0956  0.0802  0.1618   
180  0.0310  0.0221  0.0433  0.0191  0.0964  0.1827  0.1106  0.1702  0.2804   
181  0.0423  0.0321  0.0709  0.0108  0.1070  0.0973  0.0961  0.1323  0.2462   
182  0.0095  0.0308  0.0539  0.0411  0.0613  0.1039  0.1016  0.1394  0.2592   
183  0.0096  0.0404  0.0682  0.0688  0.0887  0.0932  0.0955  0.2140  0.2546   
184  0.0269  0.0383  0.0505  0.0707  0.1313  0.2103  0.2263  0.2524  0.3595   
185  0.0340  0.0625  0.0381  0.0257  0.0441  0.1027  0.1287  0.1850  0.2647   
186  0.0209  0.0191  0.0411  0.0321  0.0698  0.1579  0.1438  0.1402  0.3048   
187  0.0368  0.0279  0.0103  0.0566  0.0759  0.0679  0.0970  0.1473  0.2164   
188  0.0089  0.0274  0.0248  0.0237  0.0224  0.0845  0.1488  0.1224  0.1569   
189  0.0158  0.0239  0.0150  0.0494  0.0988  0.1425  0.1463  0.1219  0.1697   
190  0.0156  0.0210  0.0282  0.0596  0.0462  0.0779  0.1365  0.0780  0.1038   
191  0.0315  0.0252  0.0167  0.0479  0.0902  0.1057  0.1024  0.1209  0.1241   
192  0.0056  0.0267  0.0221  0.0561  0.0936  0.1146  0.0706  0.0996  0.1673   
193  0.0203  0.0121  0.0380  0.0128  0.0537  0.0874  0.1021  0.0852  0.1136   
194  0.0392  0.0108  0.0267  0.0257  0.0410  0.0491  0.1053  0.1690  0.2105   
195  0.0129  0.0141  0.0309  0.0375  0.0767  0.0787  0.0662  0.1108  0.1777   
196  0.0050  0.0017  0.0270  0.0450  0.0958  0.0830  0.0879

In [6]:
iris = dataframe.values
iris

array([[0.02, 0.0371, 0.0428, ..., 0.009, 0.0032, 'R'],
       [0.0453, 0.0523, 0.0843, ..., 0.0052, 0.0044, 'R'],
       [0.0262, 0.0582, 0.1099, ..., 0.0095, 0.0078, 'R'],
       ...,
       [0.0522, 0.0437, 0.018, ..., 0.0077, 0.0031, 'M'],
       [0.0303, 0.0353, 0.049, ..., 0.0036, 0.0048, 'M'],
       [0.026, 0.0363, 0.0136, ..., 0.0061, 0.0115, 'M']], dtype=object)

In [19]:
ef = pd.DataFrame({'num_legs': [2, 4, 8, 0],
                   'num_wings': [2, 0, 0, 0],
                   'num_specimen_seen': [10, 2, 1, 8]},
                  index=['falcon', 'dog', 'spider', 'fish'])
c=ef.sample(frac=1)
c

num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
fish           0          0                  8
dog            4          0                  2
spider         8          0                  1

In [20]:
df = dataframe.sample(frac=1)

In [21]:
iris = df.values
iris

array([[0.0473, 0.0509, 0.0819, ..., 0.0028, 0.0027, 'R'],
       [0.0762, 0.0666, 0.0481, ..., 0.0107, 0.0094, 'R'],
       [0.0261, 0.0266, 0.0223, ..., 0.0028, 0.0023, 'M'],
       ...,
       [0.0587, 0.121, 0.1268, ..., 0.0228, 0.0124, 'M'],
       [0.0126, 0.0149, 0.0641, ..., 0.0116, 0.0063, 'R'],
       [0.0065, 0.0122, 0.0068, ..., 0.0006, 0.0035, 'R']], dtype=object)

In [0]:
x_train = iris[:90,:4].astype('float') 
y_train = iris[:90,4]
x_test = iris[90:,:4].astype('float')
y_test = iris[90:,4]

In [8]:
x_train.shape

(90, 4)

In [9]:
y_train.shape

(90,)

In [10]:
x_test.shape

(60, 4)

In [11]:
y_test.shape

(60,)

In [0]:
from sklearn.preprocessing import LabelEncoder
# encode class values as integers
le = LabelEncoder()
encoded_Y = le.fit_transform(y_train)
encoded_y_train = tf.keras.utils.to_categorical(encoded_Y)
encoded_Y = le.fit_transform(y_test)
encoded_y_test = tf.keras.utils.to_categorical(encoded_Y)

In [13]:
#encoded_y_train.
encoded_Y

array([0, 2, 1, 2, 2, 2, 0, 2, 0, 2, 0, 0, 0, 1, 0, 2, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 2, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 2, 0, 2, 0, 2, 1, 0, 1, 2, 2, 2, 0])

In [44]:
y_test

array(['Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', '

In [45]:
encoded_y_test

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1

In [0]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Input(shape=(4,)),
  #tf.keras.layers.Dropout(0.001),
  tf.keras.layers.Dense(8, activation='relu'),
  tf.keras.layers.Dense(3, activation='softmax')
])

In [0]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [28]:
model.fit(x_train , encoded_y_train , epochs=200)

Train on 90 samples
Epoch 1/200
90/90 [==============================] - 0s 5ms/sample - loss: 4.2758 - accuracy: 0.3556
Epoch 2/200
90/90 [==============================] - 0s 172us/sample - loss: 4.1739 - accuracy: 0.3556
Epoch 3/200
90/90 [==============================] - 0s 184us/sample - loss: 4.0770 - accuracy: 0.3556
Epoch 4/200
90/90 [==============================] - 0s 190us/sample - loss: 3.9737 - accuracy: 0.3556
Epoch 5/200
90/90 [==============================] - 0s 180us/sample - loss: 3.8742 - accuracy: 0.3556
Epoch 6/200
90/90 [==============================] - 0s 176us/sample - loss: 3.7736 - accuracy: 0.3556
Epoch 7/200
90/90 [==============================] - 0s 173us/sample - loss: 3.6673 - accuracy: 0.3556
Epoch 8/200
90/90 [==============================] - 0s 155us/sample - loss: 3.5699 - accuracy: 0.3556
Epoch 9/200
90/90 [==============================] - 0s 159us/sample - loss: 3.4707 - accuracy: 0.3556
Epoch 10/200
90/90 [==============================] - 0

In [75]:
results = model.evaluate(x_test, encoded_y_test,verbose=2)
results

60/1 - 0s - loss: 0.5410 - accuracy: 0.9500


[0.5317880551020304, 0.95]

In [0]:
i = 40
prediction =  model.predict_classes(x_test[i].reshape(1,4))

In [87]:
if prediction == 0:
  print("The data is :",x_test[i],"and I have predicted that it's a",prediction,"i.e Iris-setosa")
  print("Actual data :",x_test[i] , "actual label :",y_test[i])

elif prediction == 1:
  print("The data is :",x_test[i],"and I have predicted that it's a",prediction,"i.e Iris-versicolor")
  print("Actual data :",x_test[i] , "actual label :",y_test[i])

else:
  print("The data is :",x_test[i],"and I have predicted that it's a",prediction,"i.e Iris-virginica")
  print("Actual data :",x_test[i] , "actual label :",y_test[i])


The data is : [6.1 2.9 4.7 1.4] and I have predicted that it's a [1] i.e Iris-versicolor
Actual data : [6.1 2.9 4.7 1.4] actual label : Iris-versicolor
